name: Download File

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download File
      run: |
        wget https://s3.amazonaws.com/bucket.sakibnm.space/cy2550/bicycle-world.zip
